# conda environment file to use by default
# This must be a relative path to the top-level Snakefile directory (e.g., `ncov/`).
conda_environment: "nextstrain.yaml"

# Define files used for external configuration. Common examples consist of a reference sequence to
# align sequences to, colors for strain attributes in auspice, and auspice
# configuration files.
files:
  reference: "defaults/reference_seq.gb"
  alignment_reference: "defaults/reference_seq.fasta"
  annotation: "defaults/annotation.gff"
  include: "defaults/include.txt"
  color_schemes: "defaults/color_schemes.tsv"
  auspice_config: "defaults/auspice_config.json"
  description: "defaults/description.md"
  clades: "builds/clades.tsv"
  ordering: "builds/color_ordering.tsv"
  lat_longs: "builds/lat_longs.tsv"
  mut_fit: "builds/mutational_fitness_distance_map.json"
  pango_designations: "builds/pango_designations.csv"
  metadata_designated: "builds/metadata_designated.tsv"

data_source:
  clades: "https://raw.githubusercontent.com/nextstrain/ncov/master/defaults/clades.tsv"
  lat_longs: "https://raw.githubusercontent.com/nextstrain/ncov/master/defaults/lat_longs.tsv"
  color_ordering: "https://raw.githubusercontent.com/nextstrain/ncov/master/defaults/color_ordering.tsv"
  mut_fit: "https://raw.githubusercontent.com/nextstrain/ncov/master/defaults/mutational_fitness_distance_map.json"
  pango_designations: "https://raw.githubusercontent.com/cov-lineages/pango-designation/master/lineages.csv"

origins:
  gisaid:
    metadata: "s3://nextstrain-ncov-private/metadata.tsv.gz"
    sequences: "s3://nextstrain-ncov-private/sequences.fasta.xz"
    exclude: "https://raw.githubusercontent.com/nextstrain/ncov/master/defaults/exclude.txt"
    filters: "--min-length 27000 --min-date 2019-12-01"

tree:
  tree-builder-args: "'-ninit 10 -n 4 -czb'"

# Mask annotation
#1820  - Orf1a:519
#9430  - Orf1a:3055
#10323 - Orf1a:3353 -> removed for now
#11083 - Orf1a:3606 -> removed for now
#13019 - Orf1a:4252 -> -> removed for now
#21575 - S:5
#21614 - S:18 -> removed for now
#21846 - S:95 
#21987 - S:142
#22917 - S:452 -> removed for now
#22992 - S:477
#23012 - S:484
#23063 - S:501
#23593 - S:677 -> removed for now
#23604 - S:681
#24410 - S:950
#24642 - S:1027 -> removed for now
#26681 - M:53
#26767 - M:82 Added because it pulls Eta into Delta causing E484K reversions
#28461 - N:63 -> removed for now
#28887 - N:205 -> removed for now
#28975 - N:234  -> removed for now
mask: "--mask-from-beginning 100 --mask-from-end 50 --mask-terminal-gaps --mask-sites 1820 9430 21575 21846 21987 22992 23012 23063 23604 24410 26681 26767"
mask_hard: "--mask-from-beginning 100 --mask-from-end 50 --mask-terminal-gaps --mask-sites 21846 21987"

# Define genes to translate during alignment by nextalign.
genes: ["E","M","N","ORF1a","ORF1b","ORF3a","ORF6","ORF7a","ORF7b","ORF8","ORF9b","S"]

# TreeTime settings
refine:
  root: "Wuhan/Hu-1/2019" #EPI_ISL_402125  EPI_ISL_406798
  clock_rate: 0.0007
  clock_std_dev: 0.0003
  coalescent: "skyline"
  date_inference: "marginal"
  divergence_unit: "mutations"
  clock_filter_iqd: 4

ancestral:
  inference: "joint"

# Frequencies settings
frequencies:
  min_date: 2020.0

  # Number of months between pivots
  pivot_interval: 1

  # Measure pivots in weeks rather than months
  pivot_interval_units: "weeks"

  # KDE bandwidths in proportion of a year to use per strain.
  narrow_bandwidth: 0.05
  proportion_wide: 0.0

#
# Region-specific settings
#
traits:
  sampling_bias_correction: 2.5
  columns: ["country"]

distances:
  comparisons: ['root', 'root', 'root', 'root', 'root', 'root']
  attributes: ['S1_mutations', 'DMS_convalescent_serum', 'DMS_Class_1', 'DMS_Class_2', 'DMS_Class_3', 'ACE2_binding_site_mutations']
  maps:
    - "defaults/distance_maps/S1.json"
    - "defaults/distance_maps/convalescent_serum_mean_dms.json"
    - "defaults/distance_maps/class_1_mean_dms.json"
    - "defaults/distance_maps/class_2_mean_dms.json"
    - "defaults/distance_maps/class_3_mean_dms.json"
    - "defaults/distance_maps/ace2.json"