configfile:
  - defaults/parameters.yaml # Pull in the default values
  - profiles/focal/builds.yaml # Specific builds for this profile
  - profiles/focal/secrets.yaml # Secrets not committed to git

# Always print the commands that will be run to the screen for debugging.
printshellcmds: True
keep-going: True
reason: True
stats: stats.json

# Print log files of failed jobs
show-failed-logs: True

cluster-config: profiles/cluster/cluster.json

cluster: "sbatch --time={cluster.time} --mem={cluster.mem} --cpus-per-task={cluster.n} --qos={cluster.qos}"

jobs: 512

jobscript: profiles/cluster/submit.sh

# Set the name for the job as display in the cluster queue.
jobname: "{rulename}.{jobid}.sh"

# For local rules
cores: 4
